### ISSUE TITLE
Incompatible with jOpenDocument

### ISSUE THREAD

**Issue by exploide** [mmulqueen/odswriter#4]
I encountered an incompatibility with the Java library [jOpenDocument](http://www.jopendocument.org/). Unfortunately I don't know whether it is odswriter or jopendocument which is misbehaving.

I tried to write an ods file using odswriter:
```python
table = []
row = ["A", "B"]
table.append(row)
out_stream = io.BytesIO()
with odswriter.writer(out_stream) as out:
    out.writerows(table)
```
Then, I return this in an HTTPResponse to let someone download the ods file.

If this is opened in LibreOffice, everything is fine.

It the jOpenDocument library tries to open the ods file, the following Exception occures:
```
Exception in thread "Thread-2" java.lang.IllegalStateException: parse error
	at org.jopendocument.dom.ODPackage$1.processEntry(Unknown Source)
	at org.jopendocument.util.ZippedFilesProcessor.process(Unknown Source)
	at org.jopendocument.dom.ODPackage.<init>(Unknown Source)
	at org.jopendocument.dom.ODPackage.<init>(Unknown Source)
	at org.jopendocument.dom.spreadsheet.SpreadSheet.createFromFile(Unknown Source)
...
Caused by: org.jdom.input.JDOMParseException: Error on line 8: Präfix "style" für Attribut "style:name", das mit Elementtyp "number:time-style" verknüpft ist, ist nicht gebunden.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:533)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:865)
	... 8 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 57; Präfix "style" für Attribut "style:name", das mit Elementtyp "number:time-style" verknüpft ist, ist nicht gebunden.
```

This happens with jOpenDocument version 1.3 and 1.4 rc2.

**Comment by mmulqueen** [comment]
I'm not sure about the source of this bug. Are there any apps i could use to try to reproduce this? I've got no experience with jOpenDocument.

**Comment by exploide** [comment]
Ok, thanks for your reply. When I have time, I will create a minimal example consisting of a Python script producing an ods file with odswriter and a Java application which tries to open the file and print the first line or something like this. I think this is appropriate to reproduce the issue.

I will write here again in a couple of days.

**Comment by mmulqueen** [comment]
Thanks :-)
If you write a quick Java application that can read the ODS and then write a new CSV then we could actually built it into our automated testing, so that's something to bear in mind.

**Comment by exploide** [comment]
Hi, here is the simple Java tool which reads an ods file with jOpenDocument and writes it to a csv file. Probably it is not very robust since Java has no built-in csv writing capabilities and I didn't want to introduce more libraries but wanted to keep it simple. However it's possible to reproduce the issue following this steps:

Save this to create_ods.py:
```python
#!/usr/bin/env python3

import odswriter as ods

if __name__ == '__main__':
    rows = [
        ["Row1 ColA", "Row1 ColB"],
        ["Row2 ColA", "Row2 ColB"]
    ]
    with ods.writer("in.ods") as f:
        f.writerows(rows)
```

Save this to OdsToCsv.java:
```java
import java.io.File;
import java.io.FileWriter;

import org.jopendocument.dom.spreadsheet.Sheet;
import org.jopendocument.dom.spreadsheet.SpreadSheet;

/**
 * This class converts an ods file to csv, reading the ods file with jOpenDocument.
 */
public class OdsToCsv {
	public static void main(String[] args) {
		try {

			if(args.length < 2) {
				System.out.println("Please pass names of input ods and output csv files as commandline argument.");
				return;
			}

			FileWriter csvFile = new FileWriter(args[1]);
			File odsFile = new File(args[0]);
			final Sheet sheet = SpreadSheet.createFromFile(odsFile).getSheet(0);

			for(int i = 0; i < sheet.getRowCount(); i++) {
				for(int j = 0; j < sheet.getColumnCount(); j++) {
					csvFile.append(sheet.getCellAt(j, i).getTextValue());
					csvFile.append(',');
				}
				csvFile.append('\n');
			}

			csvFile.close();

        } catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```

Download a recent version of [jOpenDocument](http://www.jopendocument.org/downloads.html) (e.g. 1.3 or 1.4rc2) and store it beside the two source files.

```
python3 create_ods.py
javac -cp jOpenDocument-1.4rc2.jar OdsToCsv.java
java -cp .:jOpenDocument-1.4rc2.jar OdsToCsv in.ods out.csv
```

This will give you the exceptions described in my issue. Note that it works fine when opening the ods in LibreOffice and saving it to another file.

Let me know if I can do further assistance.

**Comment by mmulqueen** [comment]
Thanks for the test utility. I've fixed the bug on your test case and some other quirks I found.

Please could you have a try with this branch: mmulqueen/odswriter/tree/jopendocument_fix and tell me how it works for you.

For full compatibility, you need to specify the number of columns that you want. Please look at the updated at the Compatibility section in the new README for details.

If it all works nicely for you, I'll merge it into the master branch and release a new version on PyPI.

**Comment by exploide** [comment]
It works fine! Awesome, thank you.

**Comment by mmulqueen** [comment]
Wonderful. Version 0.4.0 in PyPI and master on Github incorporates this fix.
