### ISSUE TITLE
error when i have more cells than cols

### ISSUE THREAD

**Issue by liske1** [mmulqueen/odswriter#6]
If I have 4 columns and 2 lines (or 3)
e.g.: 
<code>tab = [["col1","col2","col2","col4"],["test1","test2","test3","test4"],["test5","test6","test7","test8"]],</code>
and use function writerows():
<code>writerows(tab)</code>
then you library print error:
"Exception: More cells than cols.". Error in line 113
and I can`t export this to file.

**Comment by mmulqueen** [comment]
@liske1 Please can you post all of the relevant code. I suspect that your code may be misusing the cols property.

**Comment by liske1** [comment]
<code>import odswriter as ods

file  = ods.writer(open("/home/laptop/Desktop/test.ods","wb"))
my_sheet = file.new_sheet("catalog",cols=3)
tab = [["date","hour","km","name"],["2015-02-03","15:32:15","123","Adda"],["2015-03-04","15:42:15","25","Jennifer"]]
my_sheet.writerows(tab)
file.close()</code>

**Comment by liske1** [comment]
```python
import odswriter as ods

file  = ods.writer(open("/home/laptop/Desktop/test.ods","wb"))
my_sheet = file.new_sheet("catalog",cols=3)
tab = [["date","hour","km","name"],["2015-02-03","15:32:15","123","Adda"],["2015-03-04","15:42:15","25","Jennifer"]]
my_sheet.writerows(tab)
file.close()
```
